
Input Configuration File: semantic_test_suite/invisible-write-test/input.cfg

*************************************************************
*************************************************************
*                        WARNING:                           *
*                                                           *
*                                                           *
*  THIS PROGRAM IS COMPILED TO RUN IN DEVELOPER TEST MODE.  *
*                                                           *
*  This mode has some missing/modified features. If you     *
*  did not mean to execute developping tests to verify/test *
*  TMunit, please type                                      *
*                                                           *
*      make clean                                           *
*      make                                                 *
*                                                           *
* on the command line in order to compile for simulations   *
* (and user defined unit tests).                            *
*                                                           *
*************************************************************
*************************************************************
Initializing STM...


-----------------------------------------------------
               EXECUTING SCHEDULE 'S'               
-----------------------------------------------------

ThreadToEnable=0, Active=1

[Th1:T1] S
[Th1:T1] W(x)
[Th1:T1] W(x,14666)
[Th1:T1]:L 
ThreadToEnable=1, Active=1
Performing context switch...

		[Th2:T2] S
		[Th2:T2] R(x)
		[Th2:T2] R(x,0)
		[Th2:T2] Try C
		[Th2:T2] C

ThreadToEnable=0, Active=1
Performing context switch...
[Th1:T1] Try C
[Th1:T1] C



-----------------------------------------------------
             TEST COMPLETES SUCCESFULLY              
-----------------------------------------------------

Shutting STM engine down...

STM internal statistics: 
========================
Thread 1: 
	Commit: 1
	CommitReadOnly: 0
	Abort: 0
	AbortWriteLocked: 0
	AbortWriteValidate: 0
	AbortReadValidate: 0
	AbortReadLocked: 0
	AbortCommitValidate: 0
	ClockOverflows: 0

Thread 2: 
	Commit: 1
	CommitReadOnly: 0
	Abort: 0
	AbortWriteLocked: 0
	AbortWriteValidate: 0
	AbortReadValidate: 0
	AbortReadLocked: 0
	AbortCommitValidate: 0
	ClockOverflows: 0

Total stats: 
	Commit: 2
	CommitReadOnly: 0
	Abort: 0
	AbortWriteLocked: 0
	AbortWriteValidate: 0
	AbortReadValidate: 0
	AbortReadLocked: 0
	AbortCommitValidate: 0
	ClockOverflows: 0

Configuration:
	LockExtent: 4

*************************************************************
*************************************************************
*                        WARNING:                           *
*                                                           *
*                                                           *
*  THIS PROGRAM IS COMPILED TO RUN IN DEVELOPER TEST MODE.  *
*                                                           *
*  This mode has some missing/modified features. If you     *
*  did not mean to execute developping tests to verify/test *
*  TMunit, please type                                      *
*                                                           *
*      make clean                                           *
*      make                                                 *
*                                                           *
* on the command line in order to compile for simulations   *
* (and user defined unit tests).                            *
*                                                           *
*************************************************************
*************************************************************


-------------------------------------------------------
The warning above is repeated to increase visibility.
-------------------------------------------------------


